main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home, name="home"),
    path('done/<int:todo_id>', views.done, name="done"),
     path('delete/<int:todo_id>', views.delete, name="delete"),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls", namespace="main"))
]

main/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    title = models.CharField(max_length=550, verbose_name="Todo title")
    done = models.BooleanField(default=False)
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['done']

main/views.py
from django.shortcuts import render, redirect
from .models import Todo
from django.contrib import messages
# Create your views here.

def home(request):
    todos = Todo.objects.all()
    if request.method == "POST":
        todo_name = request.POST.get('name')
        temp = Todo.objects.create(title=todo_name)
        if temp:
            messages.success(request, "Todo added successfully")
            return render(request, 'main/home.html',context={'todos':todos})
        else:
            messages.error(request, "Something went wrong")
            return render(request, 'main/home.html',context={'todos':todos})
    
    return render(request, 'main/home.html', context={'todos':todos})

def done(request, todo_id):
    todo = Todo.objects.get(id=todo_id)
    todo.done = True
    todo.save()
    messages.success(request, "Todo done successfully")
    return redirect("/")

def delete(request, todo_id):
    todo = Todo.objects.get(id=todo_id)
    todo.delete()
    messages.success(request, "Todo deleted successfully")
    return redirect("/")

templates/main/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"/>
    <title>Todo main app</title>
  </head>
  <body>
    <script>
        if ( window.history.replaceState ) {
            window.history.replaceState( null, null, window.location.href );
        }
    </script>
    <main class="container">
        {% if messages %}
            {% for message in messages %}
            <div class="messages">
                <article>
                    {{message}}
                    <a role="button" onclick="this.parentElement.style.display= 'none'">X</a>
                </article>
            </div>
            {% endfor %}
        {% endif%}
        <section class="add_todo">
            <form action="" method="post">
                {% csrf_token %}
                <input type="text" name="name"  minlength="3" id="name" placeholder="Enter todo name" required>
                <button type="submit">Add todo</button>
            </form>
        </section>
        <section class="todo_list">
            <ul>
                {% for todo in todos %}
                <li>
                    <h4>
                        {% if todo.done %}
                            <strike>{{todo.title}}</strike>
                        {% else %}
                            {{todo.title}}
                        {% endif %}
                    </h4>
                    <div class="actions">
                        <a href="{% url 'main:done' todo.id %}">Done</a>
                        <a href="{% url 'main:delete' todo.id %}">Delete</a>
                    </div> 
                </li>
                {% endfor %}
            </ul>
        </section>
    </main>
  </body>
</html>